#! /bin/sh

# bspc configs
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width 		0
bspc config window_gap 			12
bspc config border_radius		15
bspc config split_ratio			0.52
bspc config gapless_monocle		true
bspc config borderless_monocle		true
bspc config focus_follows_pointer	true
bspc config pointer_modifier mod5

bspc config normal_border_color '#54546D'
bspc config active_border_color '#54546D'
bspc config focused_border_color '#54546D'

bspc rule -a Rofi state=floating
bspc rule -a Org.gnome.Nautilus state=floating center=true

# start programs
xsetroot -cursor_name left_ptr
setxkbmap de
$HOME/.scripts/customizedKeymap
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
polybar -r &
eww daemon &
unclutter &
$HOME/.config/conky/Auva/start.sh &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
feh --bg-fill ~/.wallpapers/tokyo.png
xfce4-power-manager &
parcellite &
