#! /bin/sh

# bspc configs
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width 0
bspc config window_gap 12
bspc config border_radius 15
bspc config split_ratio 0.52
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4

bspc config normal_border_color '#54546D'
bspc config active_border_color '#54546D'
bspc config focused_border_color '#54546D'

bspc rule -a Rofi state=floating
bspc rule -a org.gnome.Nautilus state=floating center=true
bspc rule -a Xfce4-settings-manager state=floating center=true
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Blueberry.py state=floating center=true
bspc rule -a KeePassXC state=floating center=true
bspc rule -a feh state=floating center=true
bspc rule -a Com.github.alainm23.planner state=floating center=true
bspc rule -a baobab state=floating center=true
bspc rule -a Nextcloud state=floating center=true
bspc rule -a Virt-manager state=floating center=true
bspc rule -a Arandr state=floating center=true
bspc rule -a qpaeq state=floating center=true
bspc rule -a simple-textreader state=floating center=true
bspc rule -a Exaile state=floating center=true

# start programs
"$HOME"/.scripts/sys-reboot &
xsetroot -cursor_name left_ptr
setxkbmap de
"$HOME"/.scripts/customizedKeymap
pgrep -x sxhkd >/dev/null || sxhkd &
picom &
polybar -r &
eww daemon &
unclutter &
"$HOME"/.config/conky/Auva/start.sh &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
feh --bg-fill ~/.wallpapers/tokyo.png
xfce4-power-manager &
parcellite &
# get annoying over time ...
# flashfocus &
nextcloud --background &
