#!/bin/bash

set -e

./sys-setup.sh
./setup.sh

# Symlink files with dotbot

config="conf.yaml"
basedir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

git submodule update --init --recursive

.dotbot/bin/dotbot -d "${basedir}" -c "${config}"

