foreground   #d1c7b7
background   #101212
cursor       #d1c7b7

color0       #101212
color8       #928b80
color1       #b9615c
color9       #D49F9B
color2       #BBA577
color10      #C8B792
color3       #8a9a7b
color11      #ADB8A3
color4       #7997A4
color12      #9EB4BD
color5       #8992a7
color13      #A6A2BA
color6       #978698
color14      #AA9CAB
color7       #c5c9c5
color15      #EAEBEA
