# Tipps and tricks: https://sw.kovidgoyal.net/kitty/conf/
# - reload kitty config file: ctrl+shift+F5
# - open kitty conf file: ctrl+shift+f2

font_family      MonoLisa
italic_font      MonoLisa Regular Italic
bold_font        MonoLisa Bold
bold_italic_font MonoLisa Bold Italic
font_size 12
font_features MonoLisa-Regular -liga +calt +zero +ss04 +ss07 +ss08 +ss09
font_features MonoLisa-RegularItalic -liga +calt +zero +ss04 +ss07 +ss08 +ss09
font_features MonoLisa-Bold -liga +calt +zero +ss04 +ss07 +ss08 +ss09
font_features MonoLisa-BoldItalic -liga +calt +zero +ss04 +ss07 +ss08 +ss09

# Map symbols to font
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono

disable_ligatures always

map kitty_mod+equal     change_font_size all +1.0
map kitty_mod+minus     change_font_size all -1.0
map kitty_mod+backspace change_font_size all 0

# https://sw.kovidgoyal.net/kitty/conf/#cursor-customization
cursor none
cursor_shape beam
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval 1
cursor_stop_blinking_after 5.0

# https://sw.kovidgoyal.net/kitty/conf/#scrollback
scrollback_lines 10000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

# https://sw.kovidgoyal.net/kitty/conf/#mouse
mouse_hide_wait 0
url_color #9CABCA
url_style curly
show_hyperlink_targets yes
strip_trailing_spaces smart
# https://sw.kovidgoyal.net/kitty/actions/
mouse_map middle release ungrabbed paste_from_selection

# https://sw.kovidgoyal.net/kitty/conf/#performance-tuning
repaint_delay 5
input_delay 1
synt_to_monitor yes

enable_audio_bell no

# https://sw.kovidgoyal.net/kitty/conf/#window-layout
remember_window_size  no
initial_window_width  640
initial_window_height 400

window_border_width 0px
draw_minimal_borders no
window_margin_width 0
window_padding_width 0

include current-theme.conf
