#! /bin/sh

#:::::::::::::::::::::::Monitor Setup :::::::::::::::::::::::::::::::
main_monitor=""

#crappy polybar tabs gets removed soon ...
touch /dev/shm/polybar-tabs 
termtabs -i 4 &

bspc config merge_overlapping_monitors false 
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor -d 一 二 三 四 五

bspc config border_width         0
bspc config window_gap          25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config border_width 5
bspc config border_radius 30
bspc config focused_border_color '#1e2127'
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a mplayer2	state=floating
bspc rule -a Kupfer.py	focus=on
bspc rule -a Screenkey	manage=off
bspc rule -a Peek	state=floating
bspc rule -a QjackCtl	desktop='^10'	state=floating
bspc rule -a Pavucontrol:pavucontrol state=floating
bspc rule -a zoom state=floating
bspc rule -a feh state=floating
bspc rule -a '*:alsamixer' state=floating center=true
bspc rule -a rofi state=floating sticky=on

pgrep bspswallow || bspswallow &

sxhkd &

# Polybar
BAR=ddobbar
export ENABLE_BALANCE=true
pgrep polybar || \
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    uMONITOR=$m polybar --reload $BAR &
  done
else
  polybar --reload $BAR &
fi
