#!/bin/sh

USER="deeedob"
TOKEN="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"

notifications=$(echo "user = \"$USER:$TOKEN\"" | curl -sf -K- https://api.github.com/notifications | jq ".[].unread" | grep -c true)

if [ "$notifications" -gt 0 ]; then
    echo "$notifications"
else
    echo "0"
fi
