[general]
currency = eur
currency_symbol = €
display = price,percent_change_24h
spacer_symbol = |
; COINMARKETCAP_API_KEY env variable can alternatively be used and will take precedence

[ada]
icon = 
in_tooltip = false
price_precision = 2
change_precision = 0
volume_precision = 2

