Hover:
  ShowAKA: Yes
Diagnostics:
  UnusedIncludes: Strict
CompileFlags:
    Add: [-Wno-unused-variable,-Wno-infinite-recursion,-Wno-array-bounds,-Werror=implicit-function-declaration,-Wshadow,-Wno-shadow-field-in-constructor-modified,-Wno-shadow-ivar,-Wuninitialized,-Wunused-label,-Wunused-lambda-capture]
