CompileFlags:
  Add:
    [
      -Wall,
      -Wextra,
      -Werror,
      -Wshadow,
      -Wnon-virtual-dtor,
      -Wold-style-cast,
      -Wcast-align,
      -Wunused,
      -Woverloaded-virtual,
      -Wpedentic,
      -Wconversion,
      -Wsign-conversion,
      -Wnull-dereference,
      -Wdouble-promotion,
      -Wformat=2,
      -Wimplicit-fallthrough,
    ]
Diagnostics:
  ClangTidy:
    Add:
      [
        -*
        abseil-*,
        bugprone-*,
        google-*,
        misc-*,
        modernize-*,
        performance-*,
        portability-*,
        readability-*,
      ]
    Remove:
      [
        google-readability-braces-around-statements,
        google-readability-namespace-comments,
        google-runtime-references,
        misc-non-private-member-variables-in-classes,
        misc-const-correctness,
        modernize-return-braced-init-list,
        modernize-use-trailing-return-type,
        modernize-avoid-c-arrays,
        performance-move-const-arg,
        readability-braces-around-statements,
        readability-identifier-length,
        readability-magic-numbers,
        readability-named-parameter,
        readability-redundant-declaration,
        readability-function-cognitive-complexity,
        bugprone-narrowing-conversions,
        bugprone-easily-swappable-parameters,
        bugprone-implicit-widening-of-multiplication-result,
        bugprone-unchecked-optional-access
      ]
    CheckOptions:
      readability-identifier-naming.NamespaceCase: lower_case
      readability-identifier-naming.ClassCase: CamelCase
      readability-identifier-naming.StructCase: CamelCase
      readability-identifier-naming.TemplateParameterCase: CamelCase
      readability-identifier-naming.FunctionCase: aNy_CasE
      readability-identifier-naming.VariableCase: lower_case
      readability-identifier-naming.ClassMemberCase: lower_case
      readability-identifier-naming.ClassMemberPrefix: m_
      readability-identifier-naming.PrivateMemberPrefix: m_
      readability-identifier-naming.ProtectedMemberPrefix: m_
      readability-identifier-naming.EnumConstantCase: CamelCase
      readability-identifier-naming.EnumConstantPrefix: k
      readability-identifier-naming.ConstexprVariableCase: CamelCase
      readability-identifier-naming.ConstexprVariablePrefix:
      readability-identifier-naming.GlobalConstantCase: UPPER_CASE
      readability-identifier-naming.GlobalConstantPrefix: k
      readability-identifier-naming.MemberConstantCase: CamelCase
      readability-identifier-naming.MemberConstantPrefix: k
      readability-identifier-naming.StaticConstantCase: camelBack
      readability-identifier-naming.StaticConstantPrefix: k
      readability-implicit-bool-conversion.AllowIntegerConditions: 1
      readability-implicit-bool-conversion.AllowPointerConditions: 1
      readability-function-cognitive-complexity.IgnoreMacros: 1

  UnusedIncludes: Strict

InlayHints:
  Designators: Yes
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Hover:
  ShowAKA: Yes
