[[mgr.prepend_keymap]]
on = ["f", "w"]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

# Add https://github.com/boydaihungst/simple-tag.yazi?tab=readme-ov-file ?
