# Use custom format:
format="$python$directory$git_branch$git_status$git_commit$character"

[python]
pyenv_version_name = true

# Prompt symbols 
[character]
success_symbol = "[](#9ece6a bold)"
error_symbol = "[](#db4b4b)"
vicmd_symbol = "[](#9ece6a)"

[directory]
format = "[]($style)[[ ](bg:#1F1F28 fg:#7aa2f7)$path](bg:#1F1F28 fg:#c0caf5)[]($style)"
style = "bg:#1F1F28 fg:#1F1F28"

[git_branch]
format = "[]($style)[[ ](bg:#1F1F28 fg:#db4b4b)$branch](bg:#1F1F28 fg:#c0caf5)[]($style)"
style = "bg:#1F1F28 fg:#1F1F28"
